### ISSUE TITLE
ランドスケープにできちゃうみたい

### ISSUE THREAD

**Issue by ukkari** [mitou/mitoujr#31]
![image](https://user-images.githubusercontent.com/922729/53281710-96f4c800-3770-11e9-9525-3b988dd1e6bd.png)

**Comment by yasulab** [comment]
@ukkari Issue 立てるところ違いそう...!! 🙈 💦

**Comment by yasulab** [comment]
@ukkari FYI: Transfer issue 
![image](https://user-images.githubusercontent.com/155807/53281719-c3a8df80-3770-11e9-9eba-eddfd3107c7c.png)

**Comment by ukkari** [comment]
やべっｗ
